### PR TITLE
Fix for #170

### PR DESCRIPTION
**Pull request by palmerj**
Fix for #170

### CODE REVIEW

**Comment by strk** [comment]
I've pushed your commit to release-1.6 via 9e1d4f552f3736278a4157438dd40ed4cc7d23d3 (note I tweaked the commit log)

**Comment by strk** [comment]
I've pushed to master as d8f8cceac999983fcc03c1eb090658404eade32b, removing the CHANGELOG part.
Please file another ticket to release & package 1.6.1

**Comment by palmerj** [comment]
Yes but this change also needs to go into master. hHow will we do that?

**Comment by strk** [comment]
I did it already, directly via `git` commandline. It is commit d8f8cce

**Pull request closed without merging**
