### PR TITLE
Reorganize dvl handling

### PR DESCRIPTION
**Pull request by strk**
Replaces #115

### CODE REVIEW

**Comment by strk** [comment]
I think this is ready for review now @palmerj @iharrison

**Comment by strk** [comment]
To recap, what happens here is:
 - A temporary table is created to map proprietor identifiers from bde.crs_proprietor to new identifiers sequenced and compacted, having 2 target ids for each source id
 - Every exposure of proprietors uses the new identifiers for proprietors (one or the other based on dvl status)
 - It should not be possible to determine which identifier belongs to which dvl status
 - Same identifiers will never be reused for different proprietors

**Comment by strk** [comment]
Competing PR: #122

**Comment by palmerj** [comment]
This is on hold until a more detailed review of the DVL is done. This will be post BDE Processor migration to AWS

**Comment by l0b0** [comment]
Closing because of no resources to follow up. Please reopen if/when we have time for this.

**Pull request closed without merging**
