### PR TITLE
[linz_bde_uploader_private] LOL 3.14 remove meshblock LDS function

### PR DESCRIPTION
**Pull request by imincik**
See: https://github.com/linz/linz_bde_uploader_private/commit/22197d25215fa9ca315c0013ed0ee82e9ac69679

### CODE REVIEW

**Comment by strk** [comment]
I guess this would fail BDE integration tests, shall I merge and see ?

**Comment by strk** [comment]
From slack: this needs to be also backported to release branch, and expected LDS dumps in bde-processor-deployment integration test needs to be updated to not expect the table being dropped here.

**Comment by strk** [comment]
From Sundary meeting: we do NOT want to backport this. Not sure how we'd deal with expected LDS tables by the end of sample data load, but let's see what happens.

Rather, I guess we'll want to document *which* version of LoL is this schema tracking, as I understand this change follows LoL changes in version 3.14, correct @billgeo ?

**Comment by billgeo** [comment]
Correct @strk. I would suggest we need some way to process old, current and future versions of BDE, and still maintain revisions in the target database.

**Comment by billgeo** [comment]
Sorry hit reopen by mistake.

**Comment by strk** [comment]
@billgeo "verions of BDE" should be defined, I'm very confused about the many different components and their versioning. Let's discuss this in #53

**Comment by imincik** [comment]
> I would suggest we need some way to process old, current and future versions of BDE, and still maintain revisions in the target database.

@billgeo , if this is really required, we need spend some time on designing some serious support for LoL backwards compatibility. Ticket https://github.com/linz/linz_bde_uploader/issues/136 created.

**Pull request closed without merging**
