### PR TITLE
Fix data dictionary formatting

### PR DESCRIPTION
**Pull request by iharrison**

### CODE REVIEW

**Comment by iharrison** [comment]
Could not remove blank page despite trying a few different formatting changes.

**Review by billgeo — APPROVED** [review]
LGTM

**Comment by palmerj** [comment]
Note the formatting looks worse than https://data.linz.govt.nz/document/11012-property-and-ownership-simplified-tables-data-dictionary/

**Comment by iharrison** [comment]
> Note the formatting looks worse than https://data.linz.govt.nz/document/11012-property-and-ownership-simplified-tables-data-dictionary/

Yes. The current (old) dictionaries were done from MS Word. Generating from Markdown has its challenges...

**Pull request merged**
