### PR TITLE
Update model diagrams

### PR DESCRIPTION
**Pull request by iharrison**
Updated model diagrams to reflect changes in schema. Included as Visio and png files.

### CODE REVIEW

**Comment by iharrison** [comment]
> Thanks @iharrison we should probably also update the docs/README.md so people know what to do with the visio files.

Thanks @billgeo - good point. I've added a note to the readme.

**Review by billgeo — CHANGES_REQUESTED** [review]
Is [doc/models/simplfified_property_and_owner_data_model.png](https://github.com/linz/linz-lds-bde-schema/pull/273/files#diff-96d6717462a0cb4b405ae5df810c2dfd290bec23a2afda85b9361659616c06cc) needed? Doesn't seemed to be used anywhere and is a duplicate of [doc/models/lds_property_ownership_model.png](https://github.com/linz/linz-lds-bde-schema/pull/273/files#diff-614086ed78f09085931ae84189af2cce51a032db03e2dff72dda7c8b1d850122)

Also, there's a typo in this file doc/models/simplfified_property_and_owner_data_model.vsd

`simplfified`-> `simplified`

**Comment by billgeo** [comment]
And are system1.vsd and system2.vsd needed? I wonder if we should rename all the visio files to match the png files? Hopefully it's a 1 to 1 match.

**Comment by iharrison** [comment]
> And are system1.vsd and system2.vsd needed? I wonder if we should rename all the visio files to match the png files? Hopefully it's a 1 to 1 match.

Thanks @billgeo Yes both system models are needed, but good point about names. I have now renamed the Visio files to be consistant and match the pngs.
Also removed the duplicate simplified model/fixed the typo.

**Review by billgeo — APPROVED** [review]
Thanks @iharrison. Looks good now.

**Pull request merged**
