### PR TITLE
Use gsed in preference to sed, if available

### PR DESCRIPTION
**Pull request by strk**
Should fix building docs on OSX

### CODE REVIEW

**Comment by strk** [comment]
@billgeo does this work for you in MacOSX ?

**Comment by strk** [comment]
or can you give me access to your system to take a look ?

**Comment by billgeo** [comment]
Hi @strk . Sorry for being so slow. I've been intending to work on this. Please feel free to ping me on slack if I am blocking something. Will aim to test this tomorrow.

**Comment by billgeo** [comment]
So still getting errors.

`$ gh pr checkout 249`

```
Bills-MacBook-Pro:linz-lds-bde-schema bmnelson$ make docs
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
Loading pages (1/6)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/parcels_dataset_model.png (ignore)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/parcel_topology_dataset_model.png (ignore)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/survey_dataset_model.png (ignore)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/marks_nodes_coordinates_dataset_model.png (ignore)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/survey_observations_dataset_model.png (ignore)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/adjustments_dataset_model.png (ignore)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/system_shared_dataset_model1.png (ignore)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/system_shared_dataset_model2.png (ignore)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/title_dataset_model.png (ignore)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/title_memorial_dataset_model.png (ignore)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                                                                          
sed: 1: "/tmp/markdown-commonmar ...": invalid command code m
sed: 1: "/tmp/markdown-commonmar ...": invalid command code m
sed: 1: "/tmp/markdown-commonmar ...": invalid command code m
sed: 1: "/tmp/markdown-commonmar ...": invalid command code m
sed: 1: "/tmp/markdown-commonmar ...": invalid command code m
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
Loading pages (1/6)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/lds_property_ownership_model.png (ignore)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                                                                        
sed: 1: "/tmp/markdown-commonmar ...": invalid command code m
sed: 1: "/tmp/markdown-commonmar ...": invalid command code m
sed: 1: "/tmp/markdown-commonmar ...": invalid command code m
sed: 1: "/tmp/markdown-commonmar ...": invalid command code m
sed: 1: "/tmp/markdown-commonmar ...": invalid command code m
```

**Comment by billgeo** [comment]
Actually, ignore that. I didn't have gsed installed. It works great now.

**Review by billgeo — APPROVED** [review]
I had to install gsed. So may want to add a note to the README? Otherwise it works fine once gsed installed.

**Comment by strk** [comment]
Requirement added to README. Let me know if it is understandable for you

**Review by billgeo — APPROVED** [review]
LGTM. Thanks @strk

**Pull request merged**
