### PR TITLE
Drop LDS_MaintainSimplifiedElectoralLayers function

### PR DESCRIPTION
**Pull request by strk**
See #4

### CODE REVIEW

**Comment by strk** [comment]
Shall the following tables also be removed ?
```
road_centre_line
road_centre_line_subsection
railway_centre_line                                                                                                                                crs_street_address                                                                                                                                 street_address2
```

**Comment by palmerj** [comment]
> road_centre_line
road_centre_line_subsection
railway_centre_line 
crs_street_address
street_address2

No please keep the data for historic purposes.

**Comment by palmerj** [comment]
unaccent extension is no longer required, so you can also drop that from the support

**Comment by strk** [comment]
The data is not installed by linz-lds-bde-schema, only the tables are. You mean we don't want a dbpatch statement to _drop_ the tables, I guess ? But if I understand correctly those tables were filled by the function removed in this PR, so they would never have data in new deploys.

**Comment by strk** [comment]
Postponing this to 1.2.0 so to be able to unblock the work on splitting bde processor from db

**Comment by palmerj** [comment]
> You mean we don't want a dbpatch statement to drop the tables, I guess ?

Yes correct

**Pull request merged**
