### PR TITLE
Add issue templates - fixes #226

### LINKED ISSUE #226: Add issue templates
Particularly to ensure Data Dictionary is updated when a new feature is added.

See https://github.com/linz/ds-infra-team/issues/620

### PR DESCRIPTION
**Pull request by billgeo**
Added some issue templates. Particularly to ensure data dictionaries are updated.

### CODE REVIEW

**Comment by strk** [comment]
I hate it when I'm prompted with templates upon filing a ticket or pull request, usually it's just more time needed to remove all those lines. What's the goal ? We don't get so many issues/pull-requests that we need to guide contributors so much, it's just a few of us and we should all be aware of what it takes.

Now, for the `update data dictionary` hint, the body of these templates is not telling me HOW to do that. Do I understand correctly it's to be done only upon release ? With [few](https://git.osgeo.org/gitea/postgis/postgis/src/branch/master/HOWTO_RELEASE) [other](https://git.osgeo.org/gitea/geos/geos/src/branch/master/HOWTO_RELEASE) [projects](https://github.com/OSGeo/gdal/blob/master/gdal/HOWTO-RELEASE) we use to have an [HOWTO_RELEASE](https://github.com/OSGeo/PROJ/blob/master/HOWTO-RELEASE) file that contains instruction about releases. How about doing just that here ?

Note that I do NOT use the "Release" button to make releases for this repository so I would not even see such template.

**Comment by billgeo** [comment]
Thanks @strk. Good points. Although would leave the 'create blank issue' button there as well I think, so I guess you'd always have the option to create a blank issue. Would be interested to hear @imincik 's opinion?

> With few other projects we use to have an HOWTO_RELEASE file

I'm okay with that, although wouldn't it to duplicate anything that's in bde-processor-deployment wiki? And to keep it consistent, maybe it should be added there, although that would make it disconnected from this repo I guess.

**Comment by strk** [comment]
> > With few other projects we use to have an HOWTO_RELEASE file
> 
> I'm okay with that, although wouldn't it to duplicate anything that's in bde-processor-deployment wiki? And to keep it consistent, maybe it should be added there, although that would make it disconnected from this repo I guess.

The HOWTO_RELEASE could even just point to the wiki...

**Comment by billgeo** [comment]
Closing this and will look at other things like a HOWTO release document

**Pull request closed without merging**
