### PR TITLE
Update images from lds-full-landonline-data-dictionary-and-models-2.6.pdf

### PR DESCRIPTION
**Pull request by strk**
References #247

### CODE REVIEW

**Comment by billgeo** [comment]
Hi @strk. What is the best way to test this? `make docs`? I tried that and got a lot of errors.

```
Bills-MacBook-Pro:linz-lds-bde-schema bmnelson$ make docs
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
Loading pages (1/6)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/parcels_dataset_model.png (ignore)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/parcel_topology_dataset_model.png (ignore)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/survey_dataset_model.png (ignore)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/marks_nodes_coordinates_dataset_model.png (ignore)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/survey_observations_dataset_model.png (ignore)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/adjustments_dataset_model.png (ignore)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/system_shared_dataset_model1.png (ignore)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/system_shared_dataset_model2.png (ignore)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/title_dataset_model.png (ignore)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/title_memorial_dataset_model.png (ignore)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                                                                          
sed: 1: "/tmp/markdown-commonmar ...": invalid command code m
sed: 1: "/tmp/markdown-commonmar ...": invalid command code m
sed: 1: "/tmp/markdown-commonmar ...": invalid command code m
sed: 1: "/tmp/markdown-commonmar ...": invalid command code m
sed: 1: "/tmp/markdown-commonmar ...": invalid command code m
sed: 1: "/tmp/markdown-pdf-conve ...": invalid command code m
Loading pages (1/6)
Warning: Failed to load file:///Users/bmnelson/dev/linz-lds-bde-schema/lds_property_ownership_model.png (ignore)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                                                                        
sed: 1: "/tmp/markdown-commonmar ...": invalid command code m
sed: 1: "/tmp/markdown-commonmar ...": invalid command code m
sed: 1: "/tmp/markdown-commonmar ...": invalid command code m
sed: 1: "/tmp/markdown-commonmar ...": invalid command code m
sed: 1: "/tmp/markdown-commonmar ...": invalid command code m
```
It seems to create the PDFs but no images.

**Comment by vlindsay** [comment]
@strk Apologies I'm a bit lost as to where this has got to. I can provide you with fresh pngs for each model if you need

**Comment by strk** [comment]
@billgeo yes that's the way. CI is already doing it. File a ticket for your errors ?

@vlindsay I extracted the images from the PDF files of latest version so they should be fine. Can you read them from the files changed tab ?

**Comment by billgeo** [comment]
@strk. No sorry i didn't file a ticket.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by strk** [comment]
@bill does replacing `sed` with `gsed` help ?

**Pull request merged**
