### PR TITLE
[debian] Only depend on non-PostgreSQL tableversion and dbpatch packages

### PR DESCRIPTION
**Pull request by imincik**

### CODE REVIEW

**Comment by imincik** [comment]
Why you think user should have both agnostic and non-agnostic tableversion and dbpatch packages installed. This patch is setting dependency on one of them

**Comment by strk** [comment]
For the way packages have been organized (at the moment) the agnostic package contains the loader script. So, if you need the loader, you need the agnostic package.

lds-bde-schema packaged does PROVIDE a schema loader (linz-lds-bde-schema-loader) which _uses_ the tableversion/dbpatch loaders, and thus DEPENDS on that loader.

For this reason, we will need lds-bde-schema package to DEPEND on the agnostic packages (the ones containing the loader).

Having the non-agnostic packages installed is really not needed on the machine running the `lds-bde-schema-loader`, just on the server, if the loader is invoked without the `--no-extension` switch.

**Comment by strk** [comment]
So, my suggestion is to just drop the postgresql ones, from the list of dependencies.

**Comment by imincik** [comment]
@strk , ready to review once CI is finished

**Comment by strk** [comment]
CI fails with:
>  trying to overwrite '/usr/bin/table_version-loader', which is also in package tableversion 1.8.0-2linz~bionic1

Did you publish the corrected/updated debian packages on packagecloud ?

**Comment by imincik** [comment]
> CI fails with:
> 
> > trying to overwrite '/usr/bin/table_version-loader', which is also in package tableversion 1.8.0-2linz~bionic1
> 
> Did you publish the corrected/updated debian packages on packagecloud ?

Failed because I can't build postgresql-9.4-tableversion|dbpatch anymore. So old packages are used.

**Pull request merged**
