### PR TITLE
Add 1.9.1 CHANGELOG section, set target version to 1.9.1

### PR DESCRIPTION
**Pull request by strk**
This is required to release 1.9.1 version as per #211

### CODE REVIEW

**Comment by strk** [comment]
I just realized a branch for 1.9 was already created so I rebased this PR to release-1.9, including backport of the loader error assumptions removal fixing #209 too.

Can you please re-review @imincik  ?

**Comment by strk** [comment]
This PR is blocked on publication of new tableversion and dbpatch packages. I encoded the dependency in the github issue.

**Comment by strk** [comment]
CI troubled again here...

**Comment by imincik** [comment]
> CI troubled again here...

Rebasing issue ?

**Comment by strk** [comment]
No idea what it is, but re-running builds doesn't seem to help, nor closing/reopening the PR.
This is the kind of time one would call the support. WIll GitHub listen ?
Or how about force-pushing and not waiting for CI ?

**Comment by strk** [comment]
release-date shoudl also be changed

**Comment by strk** [comment]
I force-pushed a new rebased version, let's see if that helps

**Comment by imincik** [comment]
@strk , I decided to leave release of those small changes for next BDE Processor release.

**Comment by imincik** [comment]
Just make sure those changes are in master and will release them next time.

**Comment by imincik** [comment]
If you agree, please close this PR

**Comment by strk** [comment]
Ok, closing this one, and please see #215 to set master branch straight.
Will avoid a PR to retarget 1.9 to 1.9.1dev shall any hotfix be required

**Pull request closed without merging**
