### PR TITLE
Add tests for linz-lds-bde-schema-load

### PR DESCRIPTION
**Pull request by strk**
See #42

### CODE REVIEW

**Comment by strk** [comment]
Current failure for this is unrelated to the topic of this PR but rather related to #55 which will be fixed by #56 This is to be rebased after merge of the latter.

**Comment by strk** [comment]
This PR adds dependency (of the testing infrastructure: "make installcheck") on yet-to-be-released versions of table_version, dbpatch and linz-bde-schema. This is because the new "installcheck" rule will use their "loader" scripts to simplify things (ie: figuring out where the sql scripts are installed)

Maybe it should wait for an actual new release of those deps to be cut.

**Comment by imincik** [comment]
@strk , is there any reason why we can't install dbpatch and tableversion from LINZ public PPA ? One of advantages will be that we will always have latest version. Or is it because PPA doesn't contain required versions yet ?

**Comment by imincik** [comment]
I see, we have old versions in PPA. Would you please add ticket to migrate tests to PPA once packages will be updated there ? Thanks

**Pull request merged**
