### PR TITLE
Add real tests

### PR DESCRIPTION
**Pull request by strk**

### CODE REVIEW

**Comment by strk** [comment]
Ok the test works on my machine, it fails in travis because we're using latest release of `linz-bde-schema` which has SQL files enabling more verbosity than needed. That part is fixed in master branch of `bde-schema`, should we test against master branch of BDE from master branch of LDS-BDE schema or should I just expect the verbosity from BDE 1.0.2 here ?

Note that `make check` would only work with either BDE 1.0.2 *or* master, not for both., unless there's a way to ask pg_regress to enforce a specific client_min_messages and not allow changing it.

@imincik what's your call here, if I don't find a way to do the above ?

**Comment by strk** [comment]
Puzzling issue with table_version: https://travis-ci.org/linz/linz-lds-bde-schema/builds/238405021#L316-L319
inline:
```
! . ERROR: schema "table_version" does not exist

! table_version.ver_is_table_versioned|f

  psql:sql/99-patches.sql:81: INFO:  Applying patch BDE - 1.0.2: Create survey tables and columns for pending parcels release

+ table_version.ver_is_table_versioned|f
```

Basically `table_version` schema is not found by `dbpatch` code, but it is found outside. I dunno what i tis. It's working fine on my machine with PostgreSQL 9.6.

**Comment by strk** [comment]
From #postgresql IRC channel  on freenode:
```
17:59 < RhodiumToad> hm, iirc there was a recent bugfix related to that?
17:59 < RhodiumToad> let me check
18:00 < RhodiumToad> commit 9209e07605afe0349660447f20d83ef165cdd0ae
18:01 < RhodiumToad> that fix should be in the latest point releases
```

**Comment by imincik** [comment]
> Ok the test works on my machine, it fails in travis because we're using latest release of linz-bde-schema which has SQL files enabling more verbosity than needed. That part is fixed in master branch of bde-schema, should we test against master branch of BDE from master branch of LDS-BDE schema or should I just expect the verbosity from BDE 1.0.2 here ?

If understand it correctly, we can release new version of `linz-bde-schema` and upload it in to LINZ PPA

**Comment by strk** [comment]
@imincik for the sake of this test it's enough to get a tagged release (travis recipe is not using the PPA).
Anyway I got past that block by expecting the additional verbosity (will change this back after a new `linz-bde-schema` version is released from master branch). Current block is a but in PostgreSQL as reported in https://github.com/linz/linz-lds-bde-schema/pull/12#issuecomment-305542978 -- not sure how to work around that one.

**Comment by strk** [comment]
Ok installing extension via pg_regress seems effective, now next issue is that PostgreSQL 9.4 and 9.6 report INFO messages at different lines - see https://travis-ci.org/linz/linz-lds-bde-schema/builds/239513722

**Comment by strk** [comment]
Ok I was wrong, it was not about the PostgreSQL version but once again about the released version of `linz-bde-schema`. Will expect that version here too.

**Pull request merged**
